export const text = {
  brandName: "IRONFORGE",
  tagline: "FITNESS & PERFORMANCE",
  heroTitle: "Transform Your Body.\nTransform Your Life.",
  heroSubtitle: "Premium fitness training with world-class equipment and expert coaches. Your journey to greatness starts here.",
  aboutTitle: "About Us",
  aboutSubtitle: "MORE THAN A GYM",
  aboutText: "At IRONFORGE, we believe fitness is a lifestyle, not a destination. Founded in 2015, we've helped over 10,000 members achieve their fitness goals with state-of-the-art equipment, certified trainers, and a community that pushes you to be your best.",
  whyChooseTitle: "Why Choose IRONFORGE?",
  whyChooseItems: [
    { title: "Elite Equipment", desc: "Over $2M invested in premium Hammer Strength and Life Fitness machines." },
    { title: "Expert Coaching", desc: "NASM & ACE certified trainers with 10+ years of experience each." },
    { title: "24/7 Access", desc: "Train on your schedule with round-the-clock facility access." },
    { title: "Community", desc: "Join a tribe of 2,000+ driven individuals who push each other daily." },
  ],
  servicesTitle: "Membership Plans",
  servicesSubtitle: "CHOOSE YOUR PATH",
  plans: [
    {
      name: "Starter",
      price: "$29",
      period: "/month",
      features: ["Full gym access", "Locker room access", "Free WiFi", "1 guest pass/month"],
      popular: false,
    },
    {
      name: "Pro",
      price: "$59",
      period: "/month",
      features: ["Everything in Starter", "Group classes included", "Personal training (2x/mo)", "Nutrition consultation", "Sauna & steam room"],
      popular: true,
    },
    {
      name: "Elite",
      price: "$99",
      period: "/month",
      features: ["Everything in Pro", "Unlimited personal training", "Recovery suite access", "Priority booking", "Free merchandise"],
      popular: false,
    },
  ],
  trainersTitle: "Our Trainers",
  trainersSubtitle: "MEET THE TEAM",
  trainers: [
    { name: "Marcus Johnson", specialization: "Strength & Conditioning", experience: "12 years" },
    { name: "Sarah Mitchell", specialization: "HIIT & Functional Training", experience: "8 years" },
    { name: "David Chen", specialization: "Sports Performance", experience: "10 years" },
  ],
  contactTitle: "Get In Touch",
  contactSubtitle: "START YOUR JOURNEY",
  contactAddress: "1234 Fitness Blvd, Los Angeles, CA 90001",
  contactPhone: "+1 (800) 555-1234",
  contactEmail: "info@ironforge.fit",
  contactHours: "Mon–Fri: 5AM–11PM | Sat–Sun: 7AM–9PM",
  footerText: "© 2026 IRONFORGE Fitness. All rights reserved.",
  ctaBannerTitle: "No Joining Fee. No Contracts.",
  ctaBannerSubtitle: "Limited time offer — Start your free 7-day trial today.",
  servicesOverviewTitle: "What We Offer",
  servicesOverviewItems: [
    { icon: "💪", title: "Strength Training", desc: "Full free weights and machines area" },
    { icon: "🏃", title: "Cardio Zone", desc: "50+ premium cardio machines" },
    { icon: "🧘", title: "Group Classes", desc: "Yoga, HIIT, Spin & more" },
    { icon: "🥊", title: "Boxing Ring", desc: "Full-size ring with pro equipment" },
  ],
};
